### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [goffalex/week7proj1#1]
It looks like submitting the form without changing any inputs is resulting in an `Internal Server Error`. I think this may be a result of trying to fulfill this criteria in not quite the right way: `every form field should always show the current parameters`. [This example](https://gist.github.com/chrisvfritz/e36ba5ebf01f86537388) may help you figure out how you can fix this problem.

Let me know when the code is updated and I'll take another look.

**Comment by goffalex** [comment]
Code is updated and should be functioning properly now. I've done some optimizing as well. 

I have a followup question though. I tried finding a way to make it so the button would call a method in the app.rb to handle the calculations so I wouldn't have all the ruby code at the bottom, but I couldn't seem to find a way that would work. Generally whats the best way to go about something like that?

**Comment by chrisvfritz** [comment]
Nick work! I'm still able to get an `Internal Server Error` when submitting the form without a year, but I believe you should be able to solve this relatively quickly with [this resource](http://www.w3schools.com/tags/att_input_required.asp).

For your followup question, are you referring to [this code](https://github.com/goffalex/week7proj1/blob/master/views/index.erb#L39-L59)?

**Comment by goffalex** [comment]
Alright I've added some error checking which takes care of the error. 

Yes ideally I'd like to have that block of ruby in the app.rb file and have it execute once the submit button is pressed.

**Comment by chrisvfritz** [comment]
:+1: Much better! In the example apps I'll be showing on Monday after Spring Break, there will be a lot of cool refactors for this kind of thing. In this case though, the simplest refactor might be to do something like this in my `app.rb`:

``` ruby
@holidays = if params['year'].size > 0
  if params['month'].empty?
    if params['day'].empty?
      HolidApi.get year: params['year']
    else
      @error_message = 'You must select a month if you select a day.'
      []
    end
  elsif params['day'].empty?
    HolidApi.get month: params['month'], year: params['year']
  else
    HolidApi.get year: params['year'], month: params['month'], day: params['day']
  end
else
  @error_message = 'Please input a year.'
  []
end.flatten
```

Then in your view, all you'd need is something like this:

``` erb
<% if @holidays.any? %>

  <% @holidays.each do |holiday| %>
    <%= holiday['name'] %>
  <% end %>

<% else %>

  <%= @error_message || 'No holidays were found for the given search parameters.' %>

<% end %>
```

One other Ruby note you may find interesting: although Ruby has English-form versions of `&&` and `||`, `and` and `or` actually act differently than you might expect and typically, should rarely be used. [This video](http://www.rubytapas.com/episodes/125-And-Or) gives a great explanation.
